[package]
name = "spaghet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
nalgebra = "0.33.0"
num-traits = "0.2.19"
